image: node:latest

stages:
  - test
  - build
  - deploy

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

dummy-test:
  stage: test
  script:
    - echo "perform different test procedures ONLY THE PIPELINE SERVER(gitlab in this case)"
    - echo "it may run lint fixes, node module installs and unit test case run "
  only:
    - main

pull-main-on-ec2:
  stage: build
  script:
    - ssh -o StrictHostKeyChecking=no ec2-user@ec2-18-195-234-96.eu-central-1.compute.amazonaws.com "cd ecom-be && git checkout main && git pull"
    - echo "pulling from 'main' went well"
  only:
    - main

build-node-modules:
  stage: build
  script:
    - ssh -o StrictHostKeyChecking=no ec2-user@ec2-18-195-234-96.eu-central-1.compute.amazonaws.com "cd ecom-be && npm i"
    - echo "npm i went well"
  only:
    - main

pm2-restart:
  type: command
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no ec2-user@ec2-18-195-234-96.eu-central-1.compute.amazonaws.com "cd ecom-be && pm2 restart pm2.config.js"
    - echo "pm2-restart went well"
  only:
    - main